### ISSUE TITLE
ssh key support 

### ISSUE THREAD

**Issue by msdocs** [simple-machines/kafka-tunnel#8]
wanted to know if it is possible to use an ssh key instead of password

**Comment by thsutton** [comment]
If you check the source code you'll notice it just invokes the `ssh` command.

https://github.com/simple-machines/kafka-tunnel/blob/master/kafkatunnel.py#L77

If your ssh client and sshd server are configured to allow public key authentication by default, then it will be used.

Similarly it uses `sudo` to manage the local networking configuration:

https://github.com/simple-machines/kafka-tunnel/blob/master/kafkatunnel.py#L52

If the sudo configuration allows your user to execute the necessary commands without a password, you will not be asked to enter one.

Does that clarify things?
